### PR TITLE
Create package.json

### PR DESCRIPTION
**Pull request by FDiskas**

### CODE REVIEW

**Comment by FDiskas** [comment]
Add ability to install via `npm`
You should register this on npmjs.org website to

**Comment by FDiskas** [comment]
Closes #2

**Comment by bitofsky** [comment]
Thank you for your pr!!
I was checked browserify error.
ok, I solved but something different way :) #3 
And regist npm now. [https://www.npmjs.com/package/jquery.imagecursorzoom]

**Comment by FDiskas** [comment]
:fishing_pole_and_fish: - perfect. Thanks.

**Pull request closed without merging**
